# Generated by Django 3.2.3 on 2021-06-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart_api', '0002_auto_20210603_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
