# Generated by Django 3.2.3 on 2021-06-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart_api', '0005_auto_20210604_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='titel',
            new_name='title',
        ),
    ]
